# .github/workflows/nodejs.yml

name: Node.js CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x] # Node versions 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Code එක runner machine එකට checkout කරනවා

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3 # අදාල Node version එක setup කරනවා
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # npm dependencies cache කරනවා, pipeline එක වේගවත් වෙන්න

    - name: Install dependencies
      run: npm ci # 'npm install' වලට වඩා CI වලට හොඳයි, package-lock.json එක පාවිච්චි කරනවා

    - name: Run tests
      run: npm test
